include(${WikiExamples_SOURCE_DIR}/CMake/AddOptionalIfInLibrary.cmake)
include(${WikiExamples_SOURCE_DIR}/CMake/RequiresGitLfs.cmake)
include(${WikiExamples_SOURCE_DIR}/CMake/RequiresModule.cmake)
include(${WikiExamples_SOURCE_DIR}/CMake/RequiresSettingOff.cmake)
include(${WikiExamples_SOURCE_DIR}/CMake/RequiresSettingOn.cmake)
include(${WikiExamples_SOURCE_DIR}/CMake/RequiresVersion.cmake)
include(${WikiExamples_SOURCE_DIR}/CMake/RequiresClass.cmake)
include(${WikiExamples_SOURCE_DIR}/CMake/RequiresTarget.cmake)
